name: pr-stopship

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

      - name: Test
        shell: bash {0}
        env:
          IS_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          if [[ $IS_MERGED == true ]]
          then
            echo would cherry pick
          fi
