name: pr-stopship

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set new version
        id: bump-version
        run: exit 1

      - name: Disable "include administrators" on prod/candidate
        uses: benjefferies/branch-protection-bot@1.0.7
        if: always()
        continue-on-error: true
        with:
            access_token: ${{ secrets.GH_TOKEN }}
            branch: prod/candidate
                  
      - name: Test
        if: steps.bump-version.outputs.exit_code == 0
        run: echo I ran
